openapi: 3.0.0
info:
  title: API de Boletas, Quekiwi
  version: 1.0.0
  description: Contiene las API REST para crear y cancelar una boleta
  contact:
    email: devteam@quekiwi.com
    name: Equipo de desarrollo
servers:
  - url: http://localhost:8082
    variables: {}
    description: Local
  - url: http://api.quekiwi.com
    variables: {}
    description: Produccion
paths:
  /boletas/{id}:
    get:
      summary: Detalle de boleta
      description: ""
      operationId: detalleBoleta
      parameters:
        - in: path
          name: id
          schema:
            type: integer
          required: true
      responses:
        "200":
          description: ok
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Boleta"
        "404":
          description: Not found
      tags:
        - Boletas
    delete:
      summary: Cancele una boleta
      description: ""
      operationId: cancelarBoleta
      parameters:
        - in: path
          name: id
          schema:
            type: integer
          required: true
      responses:
        "204":
          description: No content
      tags:
        - Boletas
  /boletas:
    post:
      summary: Registro una boleta
      description: ""
      operationId: registrarBoleta
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/BoletaCrearRequest"
      responses:
        "201":
          description: created
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Boleta"
      tags:
        - Boletas
    get:
      summary: Lista boletas
      description: ""
      operationId: listaBoletas
      responses:
        "200":
          description: ok
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/Boleta"
      tags:
        - Boletas
components:
  schemas:
    LineaBoleta:
      type: object
      properties:
        mascotaId:
          type: integer
          format: int64
        veterinarioId:
          type: integer
          format: int64
        servicioId:
          type: integer
          format: int64
    Boleta:
      type: object
      properties:
        id:
          type: integer
          format: int64
        nombreComprador:
          type: string
        total:
          type: number
        lineas:
          type: array
          items:
            $ref: "#/components/schemas/LineaBoleta"
    BoletaCrearRequest:
      type: object
      properties:
        nombreComprador:
          type: string
        lineas:
          type: array
          items:
            $ref: "#/components/schemas/LineaBoleta"
